version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  frontend:
    image: crycry142/foodgram_frontend
    volumes:
      - static:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: crycry142/foodgram_gateway
    ports:
      - "88:80"
    volumes:
      - static:/usr/share/nginx/html/
      # - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/media
    depends_on:
      - frontend
  db:
    image: postgres:13
    env_file: prod.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: crycry142/foodgram_backend
    env_file: prod.env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
