# Generated by Django 4.2.4 on 2023-09-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(check=models.Q(('color__regex', '^#[a-fA-F0-9]{6}$')), name='color_in_HEX'),
        ),
    ]
