# Generated by Django 4.2.4 on 2023-09-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_shoppingcart_favouriterecipes_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 1)), name='min_amount = 1'),
        ),
    ]
